<!-- Breadcomb area Start-->
<?php
    
    $this->partial('notika/breadcump-area.phtml');
    
?>
<!-- Breadcomb area End-->
<!-- Form Examples area start-->
<div class="form-example-area">
    <form id="login" method="post" action="#">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-example-wrap mg-t-30">
                        <div class="cmp-tb-hd cmp-int-hd">
                            <h2>Ação</h2>
                        </div>

                        <div class="form-example-wrap mg-t-30">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="form-group">
                                            <div class="nk-int-st">
                                                    <?= $this->helper('html')->select(
                                                            'profile_id',
                                                            $profiles->getList(),
                                                            ['class' => 'selectpicker form-control input-sm', 'required' => true]
                                                        );
                                                    ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="form-group">
                                            <div class="nk-int-st">
                                                    <?= $this->helper('html')->select(
                                                            'permission_id',
                                                            $permissions->getList(),
                                                            ['class' => 'selectpicker form-control input-sm', 'required' => true]
                                                        );
                                                    ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="fm-checkbox">
                                            <label><input name="action[view]" type="checkbox" class="i-checks"> Ver</label>
                                        </div>
                                    </div>
                                </div>  
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="fm-checkbox">
                                            <label><input name="action[list]" type="checkbox" class="i-checks"> Listar</label>
                                        </div>
                                    </div>
                                </div> 
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="fm-checkbox">
                                            <label><input name="action[insert]" type="checkbox" class="i-checks"> Criar</label>
                                        </div>
                                    </div>
                                </div> 
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="fm-checkbox">
                                            <label><input name="action[update]" type="checkbox" class="i-checks"> Mudar</label>
                                        </div>
                                    </div>
                                </div> 
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="fm-checkbox">
                                            <label><input name="action[delete]" type="checkbox" class="i-checks"> Excluir</label>
                                        </div>
                                    </div>
                                </div> 
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="fm-checkbox">
                                            <label><input name="action[download]" type="checkbox" class="i-checks"> Baixar</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="form-example-int form-example-st">
                                        <div class="fm-checkbox">
                                            <label><input name="action[upload]" type="checkbox" class="i-checks"> Subir</label>
                                        </div>
                                    </div>
                                </div>                          
                            </div>
                        </div>

                        <div class="form-example-wrap mg-t-30">
                            <div class="row"> 
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="form-example-int">
                                        <button name="Y3JpYcOnw6NvIGRlIGHDp8O1ZXMgcGVybWl0aWRhcw==" class="btn btn-success notika-btn-success">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- Form Examples area End-->
