<div>
                    <div class="card">
                        <div class="card-header">
                            <strong>Area</strong>
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="text-input" class=" form-control-label"><span style="color:red;">*</span>Slug:</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" id="slug" name="slug" value="<?= $area->getField('slug'); ?>" placeholder="" class="form-control">
                                        <small class="form-text text-muted">Nome identificador da area.</small>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="text-input" class=" form-control-label"><span style="color:red;">*</span>Etiqueta:</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" id="label" name="label" value="<?= $area->getField('label'); ?>" placeholder="" class="form-control">
                                        <small class="form-text text-muted">Etiqueta da area.</small>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="text-input" class=" form-control-label">Descrição:</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" id="description" name="description" value="<?= $area->getField('description'); ?>" placeholder="" class="form-control">
                                        <small class="form-text text-muted">Descrição da area.</small>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <input type="hidden" id="area_id" name="area_id" value="<?= !empty($area->getField('area_id'))? $area->getField('area_id'): null; ?>" class="form-control">
                                    <button type="submit" name="YXJlYVVwZGF0ZQ==" class="btn btn-primary btn-sm">
                                        <i class="fa fa-dot-circle-o"></i> Enviar
                                    </button>
                                    <button type="reset" class="btn btn-danger btn-sm">
                                        <i class="fa fa-ban"></i> Limpar
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                        <p>Copyright © 2020 DOUGGS. All rights reserved.</p>
                        </div>
                    </div>
                </div>