                    <?php
                        if(isset($menus)){
                    ?>
                    <div class="header__navbar">
                        <ul class="list-unstyled">
                            <?php
                                $sectionId = null;
                                while(!$menus->isEof()){
                                    if($sectionId != $menus->getField('section_id')){
                                        if(isset($sectionId)){
                                            $mn .= '</ul>
                                                </li>';
                                            echo $mn;
                                        }
                                        $mn = '';
                                        $mn .= '<li class="has-sub">';
                                        $mn .= '<a href="#"><i class="fas '.$menus->getField('section_icon').'"></i>'.$menus->getField('section_label').'<span class="bot-line"></span></a>
                                            <ul class="header3-sub-list list-unstyled">';
                                    }
                                    $mn .= "\n".'<li><a href="'._root.$menus->getField('url').'">'.$menus->getField('label').'</a></li>';

                                    $sectionId = $menus->getField('section_id');
                                    $menus->next();
                                }
                                $mn .= "\n".'</ul>
                                    </li>'."\n";
                                echo $mn;
                            ?>
                        </ul>
                    </div>
                    <?php
                        }
                    ?>