            <?php
                if(isset($menus)){
            ?>
            <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">
                    <?php
                        $sectionId = null;
                        while(!$menus->isEof()){
                            if($sectionId != $menus->getField('section_id')){
                                if(isset($sectionId)){
                                    $mn .= '</ul>
                                        </li>';
                                    echo $mn;
                                }
                                $mn = '';
                                $mn .= '<li class="has-sub">';
                                $mn .= '<a class="js-arrow" href="#"><i class="fas '.$menus->getField('section_icon').'"></i>'.$menus->getField('section_label').'</a>
                                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">';
                            }
                            $mn .= "\n".'<li><a href="'._root.$menus->getField('url').'">'.$menus->getField('label').'</a></li>';

                            $sectionId = $menus->getField('section_id');
                            $menus->next();
                        }
                        $mn .= "\n".'</ul>
                            </li>'."\n";
                        echo $mn;
                    ?>
                    </ul>
                </div>
            </nav>
            <?php
                }
            ?>
