                <div>
                    <div class="card">
                        <div class="card-header">
                            <strong>Lista</strong><small> Permissões</small>
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="company" class=" form-control-label">Perfil</label>
                                            <select name="profile_id" id="profile_id" class="form-control">
                                                <option value="0">Please select</option>
                                                <option value="1">Option #1</option>
                                                <option value="2">Option #2</option>
                                                <option value="3">Option #3</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="vat" class=" form-control-label">Area</label>
                                            <select name="area_id" id="area_id" class="form-control">
                                                <option value="0">Please select</option>
                                                <option value="1">Option #1</option>
                                                <option value="2">Option #2</option>
                                                <option value="3">Option #3</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="vat" class=" form-control-label">Ação</label>
                                            <select name="action_slug" id="action_slug" class="form-control">
                                                <option value="0">Please select</option>
                                                <option value="1">Option #1</option>
                                                <option value="2">Option #2</option>
                                                <option value="3">Option #3</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" name="cGVybWlzc2lvbkxpc3Q=" class="btn btn-primary btn-sm">
                                        <i class="fa fa-dot-circle-o"></i> Buscar
                                    </button>
                                    <button type="reset" class="btn btn-danger btn-sm">
                                        <i class="fa fa-ban"></i> Limpar
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">Navegação</strong>
                        </div>
                        <div class="card-body">
                            <div class="row form-group">
                                <div class="col-2">
                                    <a target="_blank" href="<?= _root ?>/admin/permissions/permissionNew" class="btn btn-sm btn-outline-primary">Novo</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- DATA TABLE-->
                    <div class="table-responsive m-b-40">
                        <table class="table table-borderless table-data3">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Perfil</th>
                                    <th>Area</th>
                                    <th>Ação</th>
                                    <th>...</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    if(isset($registros)){
                                        while(!$registros->isEof()){
                                ?>
                                <tr>
                                    <td><a href="<?= _root ?>/admin/permissions/permission/<?= $registros->getField('permission_id') ?>"><?= $registros->getField('permission_id') ?></a></td>
                                    <td><?= $profile_id  = $registros->profile()->getField('label'); ?></td>
                                    <td><?= $area_id     = $registros->area()->getField('label') ?></td>
                                    <td><?= $action_slug = $registros->actionSlug()->getField('label') ?></td>
                                    <td></td>
                                </tr>
                                <?php
                                            $registros->next();
                                        }
                                    }
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <!-- END DATA TABLE-->

                    <div class="row">
                        <div class="col-md-12">
                            <div class="copyright">
                            <p>Copyright© 2020 DOUGGS. All rights reserved.</p>
                            </div>
                        </div>
                    </div>
                </div>