                <div>
                    <div class="card">
                        <div class="card-header">
                            <strong>Permissão</strong>
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="select" class=" form-control-label">Perfil</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <select name="profile_id" id="profile_id" class="form-control" required >
                                            <option value="0">Please select</option>
                                            <option value="1">Option #1</option>
                                            <option value="2">Option #2</option>
                                            <option value="3">Option #3</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="select" class=" form-control-label">Area</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <select name="area_id" id="area_id" class="form-control" required >
                                            <option value="0">Please select</option>
                                            <option value="1">Option #1</option>
                                            <option value="2">Option #2</option>
                                            <option value="3">Option #3</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Ação</label>
                                    </div>
                                    <div class="col col-md-9">
                                        <select name="action_slug[]" id="action_slug[]" class="form-control" required>
                                            <option value="0">Please select</option>
                                            <option value="1">Option #1</option>
                                            <option value="2">Option #2</option>
                                            <option value="3">Option #3</option>
                                            <option value="4">Option #4</option>
                                            <option value="5">Option #5</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <input type="hidden" id="permission_id" name="permission_id" value="<?= !empty($profile->getField('permission_id'))? $profile->getField('permission_id'): null; ?>" class="form-control">
                                    <button type="submit" name="cGVybWlzc2lvblVwZGF0ZQ==" class="btn btn-primary btn-sm">
                                        <i class="fa fa-dot-circle-o"></i> Enviar
                                    </button>
                                    <button type="reset" class="btn btn-danger btn-sm">
                                        <i class="fa fa-ban"></i> Limpar
                                    </button>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                        <p>Copyright © 2020 DOUGGS. All rights reserved.</p>
                        </div>
                    </div>
                </div>