                <div>
                    <div class="card">
                        <div class="card-header">
                            <strong>Permissão</strong>
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="select" class=" form-control-label">Perfil</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <?= $html->select('profile_id', $profiles, array('class' => 'form-control', 'required' => 'required'), $permission[0]['profile_id']); ?>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="select" class=" form-control-label">Area</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <?= $html->select('area_id', $areas, array('class' => 'form-control', 'required' => 'required'), $permission[0]['area_id']); ?>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Ação</label>
                                    </div>
                                    <div class="col col-md-9">
                                        <?= $html->multiSelect('action[]', $actions, array('class' => 'form-control', 'required' => 'required'), explode(',', $permission[0]['actions'])); ?>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" name="cGVybWlzc2lvblVwZGF0ZQ==" class="btn btn-primary btn-sm">
                                        <i class="fa fa-dot-circle-o"></i> Enviar
                                    </button>
                                    <button type="reset" class="btn btn-danger btn-sm">
                                        <i class="fa fa-ban"></i> Limpar
                                    </button>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                        <p>Copyright © 2020 DOUGGS. All rights reserved.</p>
                        </div>
                    </div>
                </div>