                <div>
                    <div class="card">
                        <div class="card-header">
                            <strong>Perfil</strong>
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="text-input" class=" form-control-label"><span style="color:red;">*</span>Nome:</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" id="name" name="name"  value="<?= !empty($profile->getField('name'))? $profile->getField('name'): null; ?>" placeholder="Nome..." class="form-control" required>
                                        <small class="form-text text-muted">Nome do perfil</small>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="text-input" class=" form-control-label"><span style="color:red;">*</span>Etiqueta:</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" id="label" name="label"  value="<?= !empty($profile->getField('label'))? $profile->getField('label'): null; ?>" placeholder="Etiqueta..." required class="form-control">
                                        <small class="form-text text-muted">Etiqueta do perfil</small>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="text-input" class=" form-control-label">Descrição:</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" id="description" name="description"  value="<?= !empty($profile->getField('description'))? $profile->getField('description'): null; ?>" placeholder="Descrição..." class="form-control">
                                        <small class="form-text text-muted">Descrição do perfil</small>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <input type="hidden" id="profile_id" name="profile_id" value="<?= !empty($profile->getField('profile_id'))? $profile->getField('profile_id'): null; ?>" class="form-control">
                                    <button type="submit" name="cHJvZmlsZVVwZGF0ZQ==" class="btn btn-primary btn-sm">
                                        <i class="fa fa-dot-circle-o"></i> Enviar
                                    </button>
                                    <button type="reset" class="btn btn-danger btn-sm">
                                        <i class="fa fa-ban"></i> Limpar
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                        <p>Copyright © 2020 DOUGGS. All rights reserved.</p>
                        </div>
                    </div>
                </div>