                <div>
                    <div class="card">
                        <div class="card-header">
                            <strong>Perfil</strong>
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="text-input" class=" form-control-label"><span style="color:red;">*</span>Nome:</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" id="name" name="name" placeholder="Nome..." class="form-control">
                                        <small class="form-text text-muted">Nome do perfil</small>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label for="text-input" class=" form-control-label">Descrição:</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" id="description" name="description" placeholder="Descrição..." class="form-control">
                                        <small class="form-text text-muted">Descrição do perfil</small>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" name="cHJvZmlsZQ==" class="btn btn-primary btn-sm">
                                        <i class="fa fa-dot-circle-o"></i> Enviar
                                    </button>
                                    <button type="reset" class="btn btn-danger btn-sm">
                                        <i class="fa fa-ban"></i> Limpar
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                        <p>Copyright © 2020 DOUGGS. All rights reserved.</p>
                        </div>
                    </div>
                </div>